### PR TITLE
[F] Build mobile accordion component

### PR DESCRIPTION
**Pull request by 1aurend**
@jen-castiron Here's a first pass on the Accordion component. Right now the styles are tightly coupled to the component. I think it would be easy to split this out into an unstyled `BaseAccordion` and `Accordion` like we have for Dropdown, but I thought it might be better to wait on that until we implement it in  more than one place and see what we need.

### CODE REVIEW

**Comment by 1aurend** [comment]
One other question: The `details` element maintains its open/close state if you close and then re-open the whole mobile menu. Is that expected, or should I look into closing the accordions when the menu closes?

**Comment by jen-castiron** [comment]
I'm still not sure if the details/summary components should be used in a navigation menu... @dananjohnson , what do you think? It might be better (a11y wise) to make a custom disclosure, like this one: https://adrianroselli.com/2019/06/link-disclosure-widget-navigation.html or Reakit's disclosure: https://reakit.io/docs/disclosure/

**Comment by jen-castiron** [comment]
To answer your question - yes, if `details` is open it will remain open.

**Comment by dananjohnson** [comment]
Interesting. I can't think of a specific a11y issue with using the `details` element for a menu, but it does seem unconventional. FWIW this is how we handled mobile submenus on OFB, though I can't quite tell if that's how you're using it here, or for the open/close state of the whole menu.

**Pull request merged**
