### PR TITLE
Next

### PR DESCRIPTION
**Pull request by jen-castiron**
[F] Add new enable and disable buttons to Ordering rows (see https://wdp-admin-git-next-cast-iron.vercel.app/collections/9GPKwePSXkV3TO52h2by8Tap8V3XQOd/manage/order?order=PUBLISHED_ASCENDING)
[C] Upgrade tables to @tanstact/react-table v8 (all tables have been touched by this change)
[F] Build EntitySelectorDisclosure (see https://wdp-admin-git-next-cast-iron.vercel.app/contributors/J6GNobp5TD7yBUwZdt0DJ7C5zP7Q2azL/collections?order=RECENT&drawer=addContributorContribution&drawerSlug=J6GNobp5TD7yBUwZdt0DJ7C5zP7Q2azL&drawerContributionType=collection)
[F] Add search to contributors list (see https://wdp-admin-git-next-cast-iron.vercel.app/contributors)

### CODE REVIEW

**Comment by jen-castiron** [comment]
@zdavis & @1aurend , I added you as reviewers for some extra QA. I've tested these out, but just need an extra set of 👀  merging into main.

**Comment by 1aurend** [comment]
@jen-castiron This looks good to me!

**Comment by zdavis** [comment]
Hey @jen-castiron, when I select an entity using the entity selector, the value that gets populated in the field after selection seems awkward to me. Does it have to be the ID? How will users see what's been selected with this?

image

**Comment by zdavis** [comment]
Not sure if it's related to this branch, but I found a few tables where sorting doesn't work.

Unable to order by name: https://wdp-admin-git-next-cast-iron.vercel.app/items/vLrXdpghRP3uo3v7I4Ro3uzp1pm6Ovp/manage/files?order=

Unable to oder by created at: https://wdp-admin-git-next-cast-iron.vercel.app/collections/49L0G87homdbCOpVIKgmqSo2X7gJw2R/manage/order?order=

Unable to order by email: https://wdp-admin-git-next-cast-iron.vercel.app/collections/49L0G87homdbCOpVIKgmqSo2X7gJw2R/manage/access?inherited=true&order=

I was able to order tables of items as expected. Might want to double check places where ordering is setup and make sure it's working as expected.

**Comment by 1aurend** [comment]
> Hey @jen-castiron, when I select an entity using the entity selector, the value that gets populated in the field after selection seems awkward to me. Does it have to be the ID? How will users see what's been selected with this?
> 
> image

Not sure if it's useful, but this seems to happen only if you haven't first selected an item via the typeahead. After selecting an item via the dropdown, I can open browse and titles of selected items show up as expected, but if I go straight to browse it shows the id.

**Comment by jen-castiron** [comment]
@1aurend Thank you for figuring that bug out - I saw the ID once and then couldn't replicate it again. Will fix.
@zdavis Totally related - all tables were touched with the upgrade. Thanks for checking!

**Comment by jen-castiron** [comment]
@1aurend The issue with the id value is fixed! Ready for another test.

**Comment by 1aurend** [comment]
@jen-castiron I think there might be a different issue with the entity selector now. Once I select an item— either in browse or from the typeahead list— new options no longer appear in the dropdown list if I clear the input and start typing again. I only took a quick look on the preview build, so if that's not enough info to reproduce, let me know.

**Comment by jen-castiron** [comment]
@1aurend Attempt # 2! I found the bug in the entity selector's options list, so now the input should work as expected and the name of the selected item should be displayed properly. Give it another quick go and let me know if you find anything else.

**Comment by 1aurend** [comment]
Looks good to me! 🎊

**Pull request merged**
